In [1]:
import pandas as pd
import numpy as np

In [2]:
# Importing dataset

dataset =  pd.read_csv("C:/Users/hp/Downloads/Data - Data.csv")
x = dataset.iloc[:,:-1]   # independent values
y = dataset.iloc[:,-1]    # dependent values
print(x)
print("\n",y)

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

 0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object


In [3]:
# Replacing missing values
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x.iloc[:,1:])
x.iloc[:,1:] = imputer.transform(x.iloc[:,1:]).round(2)

print(x)

   Country    Age    Salary
0   France  44.00  72000.00
1    Spain  27.00  48000.00
2  Germany  30.00  54000.00
3    Spain  38.00  61000.00
4  Germany  40.00  63777.78
5   France  35.00  58000.00
6    Spain  38.78  52000.00
7   France  48.00  79000.00
8  Germany  50.00  83000.00
9   France  37.00  67000.00


In [4]:
# Encoding independent variable

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[1.000000e+00 0.000000e+00 0.000000e+00 4.400000e+01 7.200000e+04]
 [0.000000e+00 0.000000e+00 1.000000e+00 2.700000e+01 4.800000e+04]
 [0.000000e+00 1.000000e+00 0.000000e+00 3.000000e+01 5.400000e+04]
 [0.000000e+00 0.000000e+00 1.000000e+00 3.800000e+01 6.100000e+04]
 [0.000000e+00 1.000000e+00 0.000000e+00 4.000000e+01 6.377778e+04]
 [1.000000e+00 0.000000e+00 0.000000e+00 3.500000e+01 5.800000e+04]
 [0.000000e+00 0.000000e+00 1.000000e+00 3.878000e+01 5.200000e+04]
 [1.000000e+00 0.000000e+00 0.000000e+00 4.800000e+01 7.900000e+04]
 [0.000000e+00 1.000000e+00 0.000000e+00 5.000000e+01 8.300000e+04]
 [1.000000e+00 0.000000e+00 0.000000e+00 3.700000e+01 6.700000e+04]]


In [5]:
# Encoding dependent variable

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [6]:
# Splitting dataset into training and testing data

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 1)
print("X Train Data:\n",x_train)
print("\n\nX Test Data:\n",x_test)
print("\n\nY Train Data:\n",y_train)
print("\n\nY Test Data:\n",y_test)

X Train Data:
 [[0.000000e+00 0.000000e+00 1.000000e+00 3.878000e+01 5.200000e+04]
 [0.000000e+00 1.000000e+00 0.000000e+00 4.000000e+01 6.377778e+04]
 [1.000000e+00 0.000000e+00 0.000000e+00 4.400000e+01 7.200000e+04]
 [0.000000e+00 0.000000e+00 1.000000e+00 3.800000e+01 6.100000e+04]
 [0.000000e+00 0.000000e+00 1.000000e+00 2.700000e+01 4.800000e+04]
 [1.000000e+00 0.000000e+00 0.000000e+00 4.800000e+01 7.900000e+04]
 [0.000000e+00 1.000000e+00 0.000000e+00 5.000000e+01 8.300000e+04]
 [1.000000e+00 0.000000e+00 0.000000e+00 3.500000e+01 5.800000e+04]]


X Test Data:
 [[0.0e+00 1.0e+00 0.0e+00 3.0e+01 5.4e+04]
 [1.0e+00 0.0e+00 0.0e+00 3.7e+01 6.7e+04]]


Y Train Data:
 [0 1 0 0 1 1 0 1]


Y Test Data:
 [0 1]


In [7]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

print("X Train Data:\n",x_train)
print("\n\nX Test Data:\n",x_test)

X Train Data:
 [[ 0.          0.          1.         -0.19131098 -1.07812597]
 [ 0.          1.          0.         -0.01415774 -0.07013151]
 [ 1.          0.          0.          0.56667255  0.63356241]
 [ 0.          0.          1.         -0.30457288 -0.3078662 ]
 [ 0.          0.          1.         -1.90185617 -1.42046364]
 [ 1.          0.          0.          1.14750283  1.23265334]
 [ 0.          1.          0.          1.43791798  1.57499102]
 [ 1.          0.          0.         -0.7401956  -0.56461945]]


X Test Data:
 [[ 0.          1.          0.         -1.46623345 -0.90695713]
 [ 1.          0.          0.         -0.44978045  0.20564032]]
